### ISSUE TITLE
xWebAppPool does not implement the write property autoStart mentioned in the corresponding MOF schema file MSFT_xWebAppPool.schema.mof

### ISSUE THREAD

**Issue by getysc** [PowerShell/xWebAdministration#250]
I suddenly started seeing below issue in one of our environments. We did couple of deployments and we never had any issues. This is the first time.

**we are using xWebAdministration ModuleVersion = '1.12.0.0'**

The command Test-TargetResource of the PS module MSFT_xWebAppPool does not implement the write property autoStart mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\DscResources\MSFT_xWebAppPool\MSFT_xWebAppPool.schema.mof. All write paramenters mentioned in the schema file must be implemented by the command Test-TargetResource.
 CategoryInfo :InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
 FullyQualifiedErrorId :WriteParameterNotImplemented
 ---> Microsoft.Management.Infrastructure.CimException: The command Test-TargetResource of the PS module MSFT_xWebAppPool does not implement the write property autoStart mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\DscResources\MSFT_xWebAppPool\MSFT_xWebAppPool.schema.mof. All write paramenters mentioned in the schema file must be implemented by the command Test-TargetResource.
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable)
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
   at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
---> (Inner Exception #0) Microsoft.Management.Infrastructure.CimException: The command Test-TargetResource of the PS module MSFT_xWebAppPool does not implement the write property autoStart mentioned in the corresponding MOF schema file C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\DscResources\MSFT_xWebAppPool\MSFT_xWebAppPool.schema.mof. All write paramenters mentioned in the schema file must be implemented by the command Test-TargetResource.
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)

**Comment by getysc** [comment]
I suddenly started seeing this issue in one of our environments. We did couple of deployments and we never had any issues. This is the first time.

**Comment by tysonjhayes** [comment]
Hello, when I've run into this type of issue before a restart of the node tends to fix the issue, unfortunately I've yet to be able to pinpoint the issue but as the code does work otherwise it tends to be an issue on the machine. Please let us know if you are still seeing the issue.

**Comment by tysonjhayes** [comment]
Are you still experiencing this issue? I haven't heard from you in a while. If we don't hear back from you in 7 days, I'll be resolving this issue.

**Comment by johlju** [comment]
Closing this as per previous comment.
